# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NavigateAgent": "02_minerl_basic_agent.ipynb"}

modules = ["agents/navigate.py"]

doc_url = "https://opencog.github.io/rocca/"

git_url = "https://github.com/opencog/rocca/tree/master/"

def custom_doc_links(name): return None
