# Usage: Follow the steps in the README file in the directory containing this file
version: "3"
services:
    workspace:
        image: synthillect/opencog-minerl
        user: opencog
        ports:
            - "5000:5000"
            - "17001:17001"
            - "18001:18001"
            - "8888:8888"
            - "5901:5901"
            - "6901:6901"
        volumes:
            - ..:/workspace:cached
            - ~/.ccache:/home/opencog/.ccache # for persisting ccache artifacts
        environment:
            - CCACHE_DIR=/home/opencog/.ccache
            - PGHOST=db # This should be the same as the link's alias
            - PGUSER=opencog_user # user created by configure-database.sh
            - TZ=$TZ # set this to your timezone
        links:
            - postgres:db
            - relex:relex
        working_dir: /workspace
        command: jupyter lab --ip="0.0.0.0" --no-browser --ServerApp.token='' --ServerApp.password=''

    postgres:
        image: opencog/postgres
        # Uncomment the following lines if you want to work on a production
        # system.
        # NOTE: The environment variable `PROD` is set `True` then the entrypoint
        # script in opencog/postgres does additional configurations.
        # environment:
        #     - PROD=True

    relex:
        image: opencog/relex
        command: /bin/sh -c "./opencog-server.sh"
